config/routes.rb
Rails.application.routes.draw do
  root "reports#index"
  
  devise_for :users

  # resources :periods     #commenting this out because I might use it later
  resources :reports, except: [:new]

  get "reports/:id/hide" => "reports#hide", as: :hide_report

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update", as: :user

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                       :bigint           not null, primary key
#  user_id                  :bigint           not null
#  period_id                :bigint           not null
#  current_committees_rocks :text
#  future_committees_rocks  :text
#  current_internal_support :text
#  future_internal_support  :text
#  current_projects         :text
#  future_projects          :text
#  current_other            :text
#  future_other             :text
#  pto                      :date
#  pvt                      :date
#  ooo                      :date
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
class Report < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :period, counter_cache: true

  scope :current_report, -> { joins(:period).where(periods: {current: true}) }
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy hide ]
  before_action :ensure_report_belongs_to_current_user, only: %i[ show edit update destroy ]
  before_action :ensure_report_is_current, only: %i[ edit update ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)
    @report.user = current_user

    # the report period is based on the created_at date
    # need to have current period be an enum or boolean for period - current, findby
    current_period = Period.first
    @report.period = current_period

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:user_id, :period_id, :current_committees_rocks, :future_committees_rocks, :current_internal_support, :future_internal_support, :current_projects, :future_projects, :current_other, :future_other, :pto, :pvt, :ooo)
    end

  def ensure_report_belongs_to_current_user
    if current_user != @report.user
      redirect_back fallback_location: root_url, alert: "You're not authorized for that."
    end
  end

  def ensure_report_is_current
    if !@report.period.current
      redirect_back fallback_location: root_url, alert: "You're not authorized for that."
    end 
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div id="edit_report_form">
  <%= form_with(model: report, local: false) do |form| %>
    <% if report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

        <ul>
          <% report.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row justify-content-center">
      <h3>Key Priorities</h3>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :current_committees_rocks, "This Week's Committees/Rocks" %>
          <%= form.text_area :current_committees_rocks, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :future_committees_rocks, "Next Week's Committees/Rocks" %>
          <%= form.text_area :future_committees_rocks, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :current_internal_support, "This Week's Internal Support" %>
          <%= form.text_area :current_internal_support, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :future_internal_support, "Next Week's Internal Support" %>
          <%= form.text_area :future_internal_support, class: "form-control"%>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :current_projects, "This Week's Projects" %>
          <%= form.text_area :current_projects, class: "form-control" %>      
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :future_projects, "Next Week's Projects" %>
          <%= form.text_area :future_projects, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :current_other, "Other Activities This Week" %>
          <%= form.text_area :current_other, class: "form-control"  %>  
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :future_other, "Other Activities Next Week" %>
          <%= form.text_area :future_other, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-3">
        <div class="form-group">
          <div class="field">
            <%= form.label :pto, "Upcoming PTO" %>
            <%= form.date_field :pto %>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="form-group">
          <div class="field">
            <%= form.label :pvt, "Upcoming PVT"%>
            <%= form.date_field :pvt %>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="form-group">
          <div class="field">
            <%= form.label :ooo, "Upcoming OOO" %>
            <%= form.date_field :ooo %>
          </div>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="actions">
          <%= form.submit "Submit Report", class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/_report.html.erb
<div id="<%=dom_id(report)%>"> 
  <div class="row">
    <h4>Week of <%= report.period.start.strftime("%B %e, %Y") %></h4>
  </div>
  <div class="row justify-content-center mb-4">
    <div class="col-md-6">
      <div>
        <strong>This Week's Committees/Rocks:</strong>
      </div>
      <div>
        <%= report.current_committees_rocks.blank? ? ("N/A") : (report.current_committees_rocks) %>
      </div>
    </div>

    <div class="col-md-6">
      <div>
        <strong>Next Week's Committees/Rocks:</strong>
      </div>
      <div>
          </div><%= report.future_committees_rocks.blank? ? ("N/A") : 
        (report.future_committees_rocks) %>
    </div>
  </div>

  <div class="row justify-content-center mb-4">
    <div class="col-md-6">
      <div>
        <strong>This Week's Internal Support:</strong>
      </div>
      <div>
          </div><%= report.current_internal_support.blank? ? ("N/A") : 
        (report.current_internal_support) %>
    </div>

    <div class="col-md-6">
      <div>
        <strong>Next Week's Internal Support:</strong>
      </div>
      <div>
          </div><%= report.future_internal_support.blank? ? ("N/A") : 
        (report.future_internal_support) %>
    </div>
  </div>

  <div class="row justify-content-center mb-4">
    <div class="col-md-6">
      <div>
        <strong>This Week's Projects:</strong>
      </div>
      <div>
        <%= report.current_projects.blank? ? ("N/A") : (report.current_projects) %>
      </div>
    </div>

    <div class="col-md-6">
      <div>
        <strong>Next Week's Projects:</strong>
      </div>
      <div>
        <%= report.future_projects.blank? ? ("N/A") : (report.future_projects) %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mb-4">
    <div class="col-md-6">
      <div>
        <strong>Other Activities This Week:</strong>
      </div>
      <div>
        <%= report.current_other.blank? ? ("N/A") : (report.current_other) %>
      </div>
    </div>

    <div class="col-md-6">
      <div>
        <strong>Other Activities Next Week:</strong>
      </div>
      <div>
        <%= report.future_other.blank? ? ("N/A") : (report.future_other) %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mb-4">
    <div class="col-md-3">
      <div>
        <strong>Upcoming PTO:</strong>
      </div>
      <div>
        <%= report.pto ? (report.pto.strftime("%B %e, %Y")) : ("N/A") %>
      </div>
    </div>

    <div class="col-md-3">
      <div>
        <strong>Upcoming PVT:</strong>
      </div>
      <div>
        <%= report.pvt ? (report.pvt.strftime("%B %e, %Y")) : ("N/A") %>
      </div>
    </div>

    <div class="col-md-3">
      <div>
        <strong>Upcoming OOO:</strong>
      </div>
      <div>
        <%= report.ooo ? (report.ooo.strftime("%B %e, %Y")) : ("N/A") %>
      </div>
    </div>
  </div>

  <% if report.period.current %>
    <div class="row justify-content-center">
      <div class ="col-md-4">
        <%= button_to "Edit Report", edit_report_path(report), class: "btn btn-primary btn-block", method: :get, remote: true %>
      </div>
    </div>
  <% else %>
    <div class="row justify-content-center">
      <%= link_to "Hide", hide_report_path(report), remote: true %>
    </div>
  <% end %>
</div>

app/views/reports/_report_row.html.erb
<div class="row" id="<%= dom_id(report) %>_row">
  <div class="col-md-3">
    Week of <%= report.period.start.strftime("%B %e, %Y") %>
  </div>
  <div class="col-md-3">
    <%= link_to 'View', report, remote: true %>
  </div>
</div>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/edit.js.erb
$("#<%=dom_id(@report)%>").replaceWith("<%= j(render "reports/form", report: @report)%>");

app/views/reports/hide.js.erb
$("#<%=dom_id(@report)%>").replaceWith("<%= j(render "reports/report_row", report: @report) %>");

app/views/reports/index.html.erb
<div class="row justify-content-between">
  <div class="col-md-4">
    <h1>Status Reports</h1>
  </div>
  <div class="col-md-3 align-self-center">
    <%= render "users/bench_status", user: current_user %>
  </div>
</div>

<hr>

<% if current_user.current_report %>
  <div class="container">
    <%= render "reports/report", report: current_user.current_report %>
  </div>
<% else %>
  <h5>You currently do not have a report to submit.</h5>
<% end %>

<hr>

<% if current_user.reports.count > 1 %>
  <div class="container">
    <div class="row">
      <h2>Previous Reports</h2>
    </div>
    <% current_user.reports.each do |report| %>
      <% if !report.period.current %>
        <%= render "reports/report_row", report: report %>
      <% end %>
    <% end %>
  </div>
<% end %>

<br>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.js.erb
$("#<%= dom_id(@report)%>_row").replaceWith("<%= j(render @report)%>");

app/views/reports/update.js.erb
$("#edit_report_form").replaceWith("<%= j(render "reports/report", report: @report)%>");